### ISSUE TITLE
DetailedServerTooltips: Discord hovering animation freezes

### ISSUE THREAD

**Issue by Huddlect** [Metalloriff/BetterDiscordPlugins#55]
I have a problem which is quite similar to but not the same as #35.

As seen on the screenshot, Discords' hovering animation sometimes doesn't disappear and also doesn't play for new hovers after. This is pretty annoying as you can't see which guilds have new messages.

![screenshot](https://user-images.githubusercontent.com/47282036/57718258-2f6a5c80-767d-11e9-967b-7230ca0c796c.png)

**Comment by Metalloriff** [comment]
Fixed in the latest update. Thank you for reporting!

**Comment by Huddlect** [comment]
Didn't update until now and it still happens from time to time, eventhough not as often as before the update

**Comment by Huddlect** [comment]
Wew that was fast

**Comment by l0c4lh057** [comment]
getting email when something happens and a notification when i get a new email

**Comment by Huddlect** [comment]
Ok I think it only happens to servers in folders if that helps
